language: android
dist: trusty
android:
  components:
    - build-tools-29.0.1
    - android-29
  licenses:
    - '.+'

before_install:
  - yes | sdkmanager "ndk-bundle"
  - yes | sdkmanager "cmake;3.10.2.4988404"
  - yes | sdkmanager "lldb;3.1"
