package pl.pk.binarizer

enum class ProcessingMode {
    ORIGINAL,
    SIMPLE_KT, SIMPLE_KT_NATIVE, SIMPLE_CPP, SIMPLE_RS,
    BRADLEY_KT, BRADLEY_KT_NATIVE, BRADLEY_CPP, BRADLEY_RS, BRADLEY_FS,
    BRADLEY_INT_KT, BRADLEY_INT_KT_NATIVE, BRADLEY_INT_CPP, BRADLEY_INT_RS, BRADLEY_INT_FS
}
